version: 2.1

docker: &docker
  - image: circleci/node:10.15.3

cache-key: &cache-key
  key: dependency-cache-primary-{{ arch }}-{{ checksum ".nvmrc" }}-{{ checksum "package-lock.json" }}

jobs:
  build:
    docker: *docker
    steps:
      - checkout
      - restore_cache: *cache-key
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          <<: *cache-key
          paths:
            - ./node_modules
      - run:
          name: Install extension dependencies
          command: npm run bootstrap -- --concurrency=2
      - run:
          name: Check code style
          command: npm run prettier-check
      - run:
          name: Linting code
          command: npm run lint
      - run:
          name: Typechecking code
          command: npm run tsc
      - run:
          name: Running unit tests
          command: npm run test
      - run:
          name: Building extension code
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./dist

workflows:
  version: 2
  all:
    jobs:
      - build
